services:
  postgresql:
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
    ports:
      - "8000:5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "pgdata"
        read_only: false
    networks:
      - "pkd-net"
      - "proxy-net"
  migrator:
    image: "${MIGRATOR_IMAGE}"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "migrator"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__mainDatabase: "Host=postgresql;Port=5432;Username=postgres;Password=${POSTGRESQL_PASSWORD};Database=mainDatabase"
    depends_on:
      postgresql:
        condition: "service_started"
    networks:
      - "pkd-net"
  datapollingservice:
    image: "${DATAPOLLINGSERVICE_IMAGE}"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "datapollingservice"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001"
      ConnectionStrings__mainDatabase: "Host=postgresql;Port=5432;Username=postgres;Password=${POSTGRESQL_PASSWORD};Database=mainDatabase"
      ASPNETCORE_URLS: "http://+:8001"
      BiznesGovKey: "${BIZNESGOVKEY}"
    depends_on:
      postgresql:
        condition: "service_started"
      migrator:
        condition: "service_completed_successfully"
    networks:
      - "pkd-net"
  webapp:
    image: "${WEBAPP_IMAGE}"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "webapp"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8005"
      ConnectionStrings__mainDatabase: "Host=postgresql;Port=5432;Username=postgres;Password=${POSTGRESQL_PASSWORD};Database=mainDatabase"
      services__datapollingservice__http__0: "http://datapollingservice:8001"
      ASPNETCORE_URLS: "http://+:8005"
    ports:
      - "8006:8005"
    depends_on:
      postgresql:
        condition: "service_started"
      migrator:
        condition: "service_completed_successfully"
    networks:
      - "pkd-net"
      - "proxy-net"
networks:
  proxy-net:
    external: true
  pkd-net:
    driver: "bridge"
    external: false
volumes:
  pgdata:
    driver: "local"
