name: "pkd-dashboard"
services:
  pkd-postgresql:
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PKD_POSTGRESQL_PASSWORD}"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "pgdata"
        read_only: false
    networks:
      - "pkd-net"
      - "proxy-net"
    restart: "unless-stopped"
  pkd-migrator:
    image: "${PKD_MIGRATOR_IMAGE}"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "pkd-migrator"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__mainDatabase: "Host=pkd-postgresql;Port=5432;Username=postgres;Password=${PKD_POSTGRESQL_PASSWORD};Database=mainDatabase"
      TZ: "Europe/Warsaw"
    depends_on:
      pkd-postgresql:
        condition: "service_started"
    networks:
      - "pkd-net"
  pkd-dashboard:
    image: "${PKD_DASHBOARD_IMAGE}"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "pkd-dashboard"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001"
      ConnectionStrings__mainDatabase: "Host=pkd-postgresql;Port=5432;Username=postgres;Password=${PKD_POSTGRESQL_PASSWORD};Database=mainDatabase"
      ASPNETCORE_URLS: "http://+:8005"
      BiznesGovKey: "${BIZNESGOVKEY}"
      TZ: "Europe/Warsaw"
    depends_on:
      pkd-postgresql:
        condition: "service_started"
      pkd-migrator:
        condition: "service_completed_successfully"
    networks:
      - "pkd-net"
      - "proxy-net"
    restart: "unless-stopped"
networks:
  proxy-net:
    external: true
  pkd-net:
    driver: "bridge"
    external: false
volumes:
  pgdata:
    driver: "local"
