// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PkdDashboard.WebApp.Data;

#nullable disable

namespace PkdDashboard.WebApp.Data.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705201408_initialApp")]
    partial class initialApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("schPkd")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PkdDashboard.WebApp.Data.Entities.CompanyCount", b =>
                {
                    b.Property<int>("PkdEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("PkdEntryId", "Day");

                    b.ToTable("CompanyCounts", "schPkd");
                });

            modelBuilder.Entity("PkdDashboard.WebApp.Data.Entities.PkdEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<char>("PkdSuffix")
                        .HasColumnType("character(1)");

                    b.Property<char>("Section")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.ToTable("PkdEntries", "schPkd");
                });

            modelBuilder.Entity("PkdDashboard.WebApp.Data.Entities.CompanyCount", b =>
                {
                    b.HasOne("PkdDashboard.WebApp.Data.Entities.PkdEntry", "PkdEntry")
                        .WithMany()
                        .HasForeignKey("PkdEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PkdEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
